development:
  adapter: postgresql
  min_messages: warning
  database: webmock_development
  pool: 5
  username: <%= `whoami` %>
  password:
  host: localhost

test:
  adapter: postgresql
  min_messages: warning
  database: webmock_test
  pool: 5
  username: <%= `whoami` %>
  password:
  host: localhost




